[package]
name = "proxy-find"
version = "0.1.0"
authors = ["Starfear"]
edition = "2018"
license = "MIT"

[dependencies]
clap = "2.33"
tokio = { version = "0.2.13", features = ["full"] }
reqwest = { version = "0.10.4", features = ["socks"] }
futures = "0.3.4"
num_cpus = "0.2"